server:
  port: 8080

spring:
  application:
    name: online-class
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/onlineclass
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  output:
    ansi:
      enabled: always